import type { PomDefinition } from '../pom-schema.js';

/**
 * Structural scaffold for Jira Cloud issue extraction.
 *
 * NOT production-ready: Jira Cloud's DOM is generated by a frequently
 * updated React bundle and selectors below are illustrative placeholders.
 * Known fragility: data-testid attributes churn across Jira Cloud releases;
 * expect breakage within weeks of a Jira platform update.
 * Maintenance cadence: re-validate quarterly, or immediately after any
 * reported extraction failure.
 */
export const jiraCloudV1Pom: PomDefinition = {
  targetApp: 'jira',
  version: 'jira-cloud-v1',
  description:
    'Extracts summary, description, status, assignee, priority, and comments from a Jira Cloud issue view.',
  navigationSteps: [
    {
      type: 'wait',
      condition: 'selector-visible',
      selector:
        '[data-testid="issue.views.issue-base.foundation.summary.heading"]',
      timeoutMs: 30_000,
    },
  ],
  extractionSteps: [
    {
      field: 'summary',
      selector:
        '[data-testid="issue.views.issue-base.foundation.summary.heading"]',
      selectorType: 'css',
      required: true,
      multiple: false,
    },
    {
      field: 'description',
      selector: '[data-testid="issue.views.field.rich-text.description"]',
      selectorType: 'css',
      required: false,
      multiple: false,
    },
    {
      field: 'status',
      selector:
        '[data-testid="issue-field-status.ui.status-view.status-button.button"]',
      selectorType: 'css',
      required: true,
      multiple: false,
    },
    {
      field: 'assignee',
      selector:
        '[data-testid="issue-field-assignee.ui.assignee-field.assignee-view"]',
      selectorType: 'css',
      required: false,
      multiple: false,
    },
    {
      field: 'priority',
      selector:
        '[data-testid="issue-field-priority.common.ui.priority-select"]',
      selectorType: 'css',
      required: false,
      multiple: false,
    },
    {
      field: 'comments',
      selector:
        '[data-testid="issue-activity-comment.ui.comment-item.comment-content"]',
      selectorType: 'css',
      required: false,
      multiple: true,
    },
  ],
  outputShape: {
    summary: { type: 'string', required: true },
    description: { type: 'string', required: false },
    status: { type: 'string', required: true },
    assignee: { type: 'string', required: false },
    priority: { type: 'string', required: false },
    comments: { type: 'array', required: false },
  },
  metadata: {
    knownFragility:
      'Jira Cloud data-testid attributes change without notice across platform releases.',
    maintenanceCadence: 'quarterly',
  },
};
